name: update

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash -CeEuo pipefail {0}

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos-arm64
            os: macos-latest
          - name: windows
            os: windows-latest
          - name: ubuntu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: bench-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: js engine run
        uses: ahaoboy/js-engine-run@v1

      - name: update readme
        run: |
          ls -l
          ls -l output
      - name: Upload ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.os }}
          path: output
  update:
    needs: [bench]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: output
          pattern: output*
          merge-multiple: true

      - name: Update README
        run: |
          ls -l output

          rm -f README.md
          cp README-TPL.tpl README.md
          for f in output/*.md; do
            name=$(basename "$f" .md)
            echo "## $name" >> README.md
            echo -e "\n" >> README.md
            cat "$f" >> README.md
            echo -e "\n" >> README.md
          done
      - name: commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "504595380@qq.com"
          git config --global user.name "ahaoboy-ci"
          git add .
          git commit -m"update"
          cat README.md
      - name: Upload README
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: README
          path: README.md
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}